version: "3.5"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - qdrant-storage:/qdrant/storage
    ports:
      - 127.0.0.1:6333:6333
      - 127.0.0.1:6334:6334

  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fangxt
    ports:
      - 23001:5432

  django:
    image: registry.cn-shanghai.aliyuncs.com/fangxt/backend:$version
    restart: on-failure
    env_file:
      - .env
    environment:
      DEBUG: 0
      SITE_URL: $site_url
      SECRET_KEY: $secret_key
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_API_BASE: $OPENAI_API_BASE
    ports:
      - "80:80"
    volumes:
      - ./runtime/test_case/:/test_case/
      - ./runtime/test_case_origin/:/test_case_origin/:ro
      - ./runtime/django_static/:/django_static/
      - ./runtime/django_logs/:/logs/

  web:
    image: registry.cn-shanghai.aliyuncs.com/fangxt/web:$version
    restart: on-failure
    ports:
      - "81:80"
    depends_on:
      - django

  fform:
    image: registry.cn-shanghai.aliyuncs.com/fangxt/fform:$version
    restart: on-failure
    ports:
      - "82:80"
    depends_on:
      - django

volumes:
  qdrant-storage:
  postgres-storage:
