version: "3.5"
services:
  db:
    container_name: db
    image: postgres:14
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fangxt

  django:
    image: registry.cn-shanghai.aliyuncs.com/fangxt/backend:0.0.12
    restart: on-failure
    env_file:
      - .env
    environment:
      DEBUG: 0
      SITE_URL: $site_url
      SECRET_KEY: $secret_key
      OPENAI_API_KEY: $OPENAI_API_KEY
      OPENAI_API_BASE: $OPENAI_API_BASE
    ports:
      - "80:80"
    volumes:
      - ./runtime/test_case/:/test_case/
      - ./runtime/test_case_origin/:/test_case_origin/:ro
      - ./runtime/django_static/:/django_static/
      - ./runtime/django_logs/:/logs/

  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=fxt1u2849759
      - MINIO_ROOT_PASSWORD=fxt5798124709321
    volumes:
      - 'minio_data:/bitnami/minio/data'

  fform:
    image: registry.cn-shanghai.aliyuncs.com/fangxt/fform:0.0.12
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  qdrant-storage:
  postgres-storage:
  minio_data:
