# Generated by Django 4.2.6 on 2023-11-26 13:28

from django.db import migrations, models
import django.db.models.deletion
import src.fform.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "prepare"),
                            ("string", "string"),
                            ("file", "file"),
                        ],
                        default=src.fform.models.Form.Status["editing"],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255, verbose_name="key")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "tip",
                    models.CharField(max_length=255, null=True, verbose_name="tip"),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("primary_string", "primary_string"),
                            ("string", "string"),
                            ("boolean", "boolean"),
                            ("file", "file"),
                        ],
                        default=src.fform.models.FormColumn.ValueType["string"],
                        max_length=255,
                    ),
                ),
                ("validator", models.JSONField(default=dict(), verbose_name="验证规则")),
            ],
        ),
        migrations.CreateModel(
            name="FormInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="表单名称")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("value_string", models.CharField(max_length=255, null=True)),
                ("value_boolean", models.BooleanField(null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fform.form"
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fform.formcolumn",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "fname",
                    models.CharField(max_length=255, null=True, verbose_name="文件原名"),
                ),
                (
                    "key",
                    models.CharField(max_length=255, unique=True, verbose_name="文件名"),
                ),
                ("in_use", models.BooleanField(default=True, verbose_name="是否在用")),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fform.form"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="formcolumn",
            name="form_interface",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fform.forminterface"
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="form_interface",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fform.forminterface"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formcolumn",
            unique_together={("form_interface", "key")},
        ),
    ]
