# Generated by Django 4.2.6 on 2023-11-26 17:09

from django.db import migrations, models
import src.fform.models


class Migration(migrations.Migration):
    dependencies = [
        ("fform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="status",
            field=models.CharField(
                choices=[
                    ("editing", "editing"),
                    ("auditing", "auditing"),
                    ("confirmed", "confirmed"),
                ],
                default=src.fform.models.Form.Status["editing"],
                max_length=255,
            ),
        ),
    ]
