# Generated by Django 4.2.6 on 2023-11-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fform", "0002_alter_form_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formvalue",
            old_name="key",
            new_name="column",
        ),
        migrations.AddField(
            model_name="formvalue",
            name="value_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fform.formfile",
            ),
        ),
        migrations.AlterField(
            model_name="formvalue",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="fform.form",
            ),
        ),
    ]
