# Generated by Django 4.2.6 on 2023-12-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fform", "0003_rename_key_formvalue_column_formvalue_value_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfile",
            name="key",
            field=models.CharField(max_length=255, verbose_name="文件名"),
        ),
    ]
