# Generated by Django 4.2.6 on 2023-12-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fform", "0004_alter_formfile_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="audit_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="submit_time",
            field=models.DateTimeField(null=True),
        ),
    ]
