# Generated by Django 4.2.6 on 2023-12-18 00:22

from django.db import migrations, models
import django.db.models.deletion
import src.fform.models


class Migration(migrations.Migration):
    dependencies = [
        ("fform", "0005_form_audit_time_form_submit_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfile",
            name="save_type",
            field=models.CharField(
                choices=[("qiniu", "qiniu"), ("minio", "minio")],
                default=src.fform.models.FormFile.SaveType["qiniu"],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="formcolumn",
            name="form_interface",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="fform.forminterface",
            ),
        ),
    ]
