# Generated by Django 4.2.6 on 2023-10-30 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QaRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.CharField(max_length=255, null=True, verbose_name="提问"),
                ),
                ("match_question", models.FloatField(null=True, verbose_name="匹配的问题")),
                ("top_score", models.FloatField(null=True, verbose_name="匹配度")),
                (
                    "answer_type",
                    models.CharField(max_length=255, null=True, verbose_name="回答方式"),
                ),
                ("answer", models.TextField(null=True, verbose_name="回答")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
