# Generated by Django 4.2.6 on 2023-10-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0002_qarecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qarecord",
            name="match_question",
            field=models.CharField(max_length=255, null=True, verbose_name="匹配的问题"),
        ),
    ]
