# Generated by Django 4.2.6 on 2023-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0004_hotquestion_platform_qarecord_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotquestion",
            name="related_questions",
            field=models.JSONField(null=True, verbose_name="相关问题"),
        ),
        migrations.AddField(
            model_name="hotquestion",
            name="similar_questions",
            field=models.JSONField(null=True, verbose_name="相似问题"),
        ),
        migrations.AddField(
            model_name="hotquestion",
            name="standard_answer",
            field=models.TextField(null=True, verbose_name="常规回答"),
        ),
    ]
