# Generated by Django 4.2.6 on 2023-11-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0006_alter_hotquestion_related_questions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QaRecordFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "attitude",
                    models.CharField(max_length=255, null=True, verbose_name="态度"),
                ),
                (
                    "message",
                    models.CharField(max_length=255, null=True, verbose_name="详细信息"),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="qa.qarecord"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
