# Generated by Django 4.2.6 on 2024-01-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0008_alter_qarecordfeedback_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotquestion",
            name="tag",
        ),
        migrations.AddField(
            model_name="hotquestion",
            name="tags",
            field=models.JSONField(null=True, verbose_name="标签"),
        ),
    ]
