# Generated by Django 4.0.3 on 2022-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='class_name',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
