# Generated by Django 4.2.6 on 2023-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_account_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="mini_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
