# Generated by Django 4.2.6 on 2023-11-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_account_mini_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="站点名称")),
                ("host", models.CharField(max_length=255, verbose_name="域名")),
                ("logo", models.CharField(max_length=255, verbose_name="logo")),
                ("wx_appid", models.CharField(max_length=255)),
                ("wx_appsecret", models.CharField(max_length=255)),
                ("qdrant_collection_name", models.CharField(max_length=255)),
                ("as_default", models.BooleanField(verbose_name="是否作为无法匹配的默认配置")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
