# Generated by Django 4.2.6 on 2023-11-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="file")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
