# Generated by Django 4.2.6 on 2023-11-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_fileupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="platform",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.platform",
            ),
        ),
    ]
