# Generated by Django 4.2.6 on 2023-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_fileupload_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(upload_to="runtimes/file"),
        ),
    ]
